In [43]:
import gin
import copy
import numpy as np
import os


import torch as T
import torch.nn as nn
import torch.nn.functional as F
from collections import namedtuple, OrderedDict

In [48]:
np.int32(2)

2

In [42]:
from collections import namedtuple
new_var = namedtuple('new_var', "x y")
another_var = new_var(10,12)
#another_var = hello
another_var._asdict()
#another_var = hello(11, 10)

OrderedDict([('x', 10), ('y', 12)])

In [32]:
def new_func() -> str:
    print(20)
    return 1

new_func()

20


1

In [22]:
class fakeNet(nn.Module):
    def __init__(self):
        super(fakeNet, self).__init__()
        self.layer1 = nn.Linear(3, 10)
        self.layer2 = nn.Linear(10, 1)
        
    def forward(self, x):
        x = nn.ReLU(self.layer1(x))
        x = nn.ReLU(self.layer2(x))
        return x
    
fake_model = fakeNet()

In [10]:
def _get_optimizer_params(optimizer: T.optim.Optimizer):
    return sum([g['params'] for g in optimizer.param_groups], [])

_get_optimizer_params(T.optim.Adam(fake_model.parameters()))

[Parameter containing:
 tensor([[ 0.5463,  0.5572, -0.4750],
         [ 0.1517,  0.4329, -0.1134],
         [ 0.1629,  0.5508,  0.3456],
         [ 0.2774,  0.0799, -0.1599],
         [-0.5589,  0.1509,  0.1222],
         [ 0.0269, -0.2055, -0.3084],
         [ 0.2345, -0.0148, -0.1097],
         [ 0.3132,  0.5123, -0.0122],
         [-0.0155,  0.5194, -0.4481],
         [ 0.1953, -0.5506, -0.2500]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5165, -0.4564, -0.4033,  0.4208,  0.1573, -0.1503,  0.2932, -0.2530,
         -0.0411, -0.4838], requires_grad=True),
 Parameter containing:
 tensor([[-0.3120,  0.0443, -0.0293,  0.2144,  0.1787,  0.1972,  0.1258, -0.2935,
          -0.2201, -0.0204]], requires_grad=True),
 Parameter containing:
 tensor([-0.0843], requires_grad=True)]

In [16]:
sum({1:"a", 2:"b"}, [])

TypeError: can only concatenate list (not "int") to list

In [ ]:
help()