In [1]:
import gin
import copy
import numpy as np
import os


import torch as T
import torch.nn as nn
import torch.nn.functional as F
from collections import namedtuple, OrderedDict
import networkx as nx

C:\Users\areeb\anaconda3\envs\msc_test\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [15]:
new_var = np.zeros(shape=5*5, dtype=np.bool8)
print(id(new_var))
print(new_var)
print(id(copy.deepcopy(new_var)))
np.random.choice()

2608324483760
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False]
2608324484816


In [24]:
T.concat([T.tensor([0,1]),T.tensor([4,5])], dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [48]:
from hidio.sac.utils import calc_default_target_entropy
from hidio.sac.TensorSpec import TensorSpec
new_tensor_spec = TensorSpec((1,4, 3))
print(new_tensor_spec.is_bounded())
new_tensor_spec

False


TensorSpec(shape=(1, 4, 3), dtype=torch.float32)

In [37]:
print("{:.2f}".format(2.5555))

2.56


In [31]:
help(T.dtype)

Help on class dtype in module torch:

class dtype(builtins.object)
 |  Methods defined here:
 |  
 |  __reduce__(...)
 |      Helper for pickle.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  is_complex
 |  
 |  is_floating_point
 |  
 |  is_signed



In [37]:
new_dtype = str
isinstance(new_dtype, str)

False

In [39]:
getattr(T, "int32")

torch.int32

In [10]:
from enum import Enum
new_var = Enum("hello", ["a","b","c"])
new_var.c

<hello.c: 3>

In [16]:
def new_func(x:int=10, y:float=11.0):
    return x*y
help(new_func)

Help on function new_func in module __main__:

new_func(x: int = 10, y: float = 11.0)



In [42]:
from collections import namedtuple
new_var = namedtuple('new_var', "x y")
another_var = new_var(10,12)
#another_var = hello
another_var._asdict()
#another_var = hello(11, 10)

OrderedDict([('x', 10), ('y', 12)])

In [32]:
def new_func() -> str:
    print(20)
    return 1

new_func()

20


1

In [22]:
class fakeNet(nn.Module):
    def __init__(self):
        super(fakeNet, self).__init__()
        self.layer1 = nn.Linear(3, 10)
        self.layer2 = nn.Linear(10, 1)
        
    def forward(self, x):
        x = nn.ReLU(self.layer1(x))
        x = nn.ReLU(self.layer2(x))
        return x
    
fake_model = fakeNet()

In [10]:
def _get_optimizer_params(optimizer: T.optim.Optimizer):
    return sum([g['params'] for g in optimizer.param_groups], [])

_get_optimizer_params(T.optim.Adam(fake_model.parameters()))

[Parameter containing:
 tensor([[ 0.5463,  0.5572, -0.4750],
         [ 0.1517,  0.4329, -0.1134],
         [ 0.1629,  0.5508,  0.3456],
         [ 0.2774,  0.0799, -0.1599],
         [-0.5589,  0.1509,  0.1222],
         [ 0.0269, -0.2055, -0.3084],
         [ 0.2345, -0.0148, -0.1097],
         [ 0.3132,  0.5123, -0.0122],
         [-0.0155,  0.5194, -0.4481],
         [ 0.1953, -0.5506, -0.2500]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5165, -0.4564, -0.4033,  0.4208,  0.1573, -0.1503,  0.2932, -0.2530,
         -0.0411, -0.4838], requires_grad=True),
 Parameter containing:
 tensor([[-0.3120,  0.0443, -0.0293,  0.2144,  0.1787,  0.1972,  0.1258, -0.2935,
          -0.2201, -0.0204]], requires_grad=True),
 Parameter containing:
 tensor([-0.0843], requires_grad=True)]

In [16]:
sum({1:"a", 2:"b"}, [])

TypeError: can only concatenate list (not "int") to list

In [ ]:
help()